title = "Segundo Concílio de Niceia"
translated_from = "Latim"
century = 8

[[chapters]]
title = "A sagrada epístola enviada pelos imperadores Constantino e Irene ao santíssimo e beatíssimo Adriano, papa da antiga Roma."

[[chapters.paragraphs]]
original = ""
translated = """
Aqueles que recebem a dignidade do império ou a honra de serem os principais pastores de nosso Senhor \ 
Jesus Cristo devem prover e cuidar daquilo que Lhe agrada, e comandar e governar o povo com zelo, \
conforme Sua vontade e beneplácito.
"""

[[chapters.paragraphs]]
original = ""
translated = """
Assim, ó, Santíssima Cabeça [da Igreja], pesa sobre nós o encargo de conhecer infalivelmente aquilo \
que Lhe pertence, para que possamos praticar essas coisas nós mesmos, pois recebemos d’Ele a dignidade \
imperial, e vós recebestes a dignidade de chefe do clero.
"""

[[chapters.paragraphs]]
original = ""
translated = """
Agora, indo mais diretamente ao ponto: vossa bênção paternal conhece o que foi feito no passado nesta \
nossa cidade real contra as veneráveis imagens — como aqueles que reinaram antes de nós as destruíram \
e as submeteram à desonra e injúria (oh, que não lhes seja imputada culpa, pois melhor lhes teria sido \
não terem posto suas mãos sobre a Igreja!) — e como seduziram e subverteram os povos destas regiões \
a concordarem com eles — sim, até mesmo em todo o Ocidente.
"""