title = "Segundo Concílio de Niceia"
translated_from = "Latim"
century = 8

[[chapters]]
title = "A sagrada epístola enviada pelos imperadores Constantino e Irene ao santíssimo e beatíssimo Adriano, papa da antiga Roma."

[[chapters.paragraphs]]
original = ""
translated = """
Aqueles que recebem a dignidade do império ou a honra de serem os principais pastores de nosso Senhor \ 
Jesus Cristo devem zelar e prover daquilo que Lhe agrada, e comandar e governar o povo com zelo, \
conforme Sua vontade e beneplácito.
"""

[[chapters.paragraphs]]
original = ""
translated = """
Assim, oh, Santíssima Cabeça [da Igreja], pesa sobre nós o encargo de discernir infalivelmente aquilo \
que Lhe pertence, para que possamos praticar essas coisas nós mesmos, pois recebemos d’Ele a dignidade \
imperial, e vós recebestes a dignidade de chefe do clero.
"""

[[chapters.paragraphs]]
original = ""
translated = """
Agora, indo mais diretamente ao ponto: vossa bênção paternal conhece o que foi feito no passado nesta \
nossa cidade real contra as veneráveis imagens — como aqueles que reinaram antes de nós as destruíram \
e as expuseram à desonra e injúria (oh, que não lhes seja imputada tal culpa, pois melhor lhes teria \
sido não tocar na Igreja!) — e como seduziram e subverteram os povos destas regiões a concordarem com \
eles — sim, até mesmo em todo o Ocidente, embora apenas até o momento em que Deus nos elevou a este \
trono, para buscar Sua glória e verdade, seguindo fielmente o que foi transmitido pelos Apóstolos e \
pelos demais doutores.
"""